name: r_tree
version: 1.0.0
description: 'A recursive RTree library written in Dart.'
authors:
  - Taylor Anderson <taylor.anderson@workiva.com>
homepage: https://github.com/Workiva/r_tree

dev_dependencies:
  benchmark_harness: any
  test: ^0.12.4
  coverage: ^0.7.3
  dart_dev: ^1.0.0
  dart_style: ">=0.2.0 <0.3.0"
  dartdoc: ">=0.8.0 <=0.10.0"
